//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by testMSVC2.rc
//
#define IDR_LIGHTS                      4
#define IDR_testMSVC2TYPE_CNTR_IP       7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_LIGHT                       101
#define IDP_FAILED_TO_CREATE            102
#define IDS_LIGHTS_VIEW                 103
#define IDS_COLOR                       104
#define IDS_ENABLED                     105
#define IDS_GL_WINDOW_TITLE             106
#define IDS_SCENE_BROWSER               107
#define ID_SCENE_BROWSER_WND            108
#define ID_SCENE_BROWSERWND             108
#define IDS_LIGHT_DIFFUSE               109
#define IDS_OTHER                       110
#define IDS_DEFAULT                     111
#define IDS_INTENSITY                   112
#define IDS_LIGHT_AMBIENT               113
#define IDS_LIGHT_SPECULAR              114
#define IDS_POSITION                    115
#define IDS_POSITIONX                   116
#define IDS_POSITIONY                   117
#define IDS_POSITIONZ                   118
#define IDR_POPUP_EDIT                  119
#define IDS_POSITIONW                   119
#define ID_STATUSBAR_PANE1              120
#define IDS_IDS_SPOTDIRECTION           120
#define IDS_SPOTDIRECTION               120
#define ID_STATUSBAR_PANE2              121
#define IDS_SPOTEXPONENT                121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_SPOTCUTOFF                  126
#define IDS_CONSTATT                    127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_LINEARATT                   129
#define IDR_testMSVC2TYPE               130
#define IDR_VSHADER_TYPE                130
#define ID_WINDOW_MANAGER               131
#define IDS_QUADRATICATT                131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define IDS_FRAGMENT_SHADER             133
#define ID_VIEW_CLASSVIEW               134
#define IDS_VERTEX_SHADER               134
#define ID_PROPERTIES                   135
#define IDS_SCENE                       135
#define ID_OPEN                         136
#define IDS_Program                     136
#define IDS_PROGRAM                     136
#define ID_OPEN_WITH                    137
#define IDS_VERTEX_PROGRAM              137
#define ID_DUMMY_COMPILE                138
#define IDS_FRAGMENT_PROGRAM            138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define IDS_PATH                        139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_PROPERTIESWND                140
#define ID_CLASS_DEFINITION             141
#define IDS_OUTPUT_TAB                  141
#define ID_CLASS_PROPERTIES             142
#define IDS_SURFACE_COLOR               142
#define ID_NEW_FOLDER                   143
#define IDS_SURFACE_SMOOTHING           143
#define ID_SORT_MENU                    144
#define IDS_SURFACE_NAME                144
#define ID_SORTING_GROUPBYTYPE          145
#define IDS_SURFACE_DOUBLESIDED         145
#define ID_SORTING_SORTALPHABETIC       146
#define IDS_SURFACE_POLYGON_COUNT       146
#define ID_SORTING_SORTBYTYPE           147
#define IDS_SURFACE_POLYGON_OFFSET      147
#define ID_SORTING_SORTBYACCESS         148
#define IDS_COLOR_MAP                   148
#define ID_VIEW_OUTPUTWND               149
#define IDS_LUMINOSITY_MAP              149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define IDS_DIFFUSE_MAP                 151
#define ID_PROPERTIES1                  152
#define IDS_SPECULAR_MAP                152
#define ID_PROPERTIES2                  153
#define IDS_GLOSSINESS_MAP              153
#define ID_EXPAND_ALL                   154
#define IDS_REFLECTION_MAP              154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDS_TRANSPARENCY_MAP            159
#define IDS_REFRACTION_MAP              160
#define IDI_FILE_VIEW                   161
#define IDS_TRANSLUCENCY_MAP            161
#define IDI_FILE_VIEW_HC                162
#define IDS_BUMP_MAP                    162
#define IDI_CLASS_VIEW                  163
#define IDS_VALUE                       163
#define IDI_CLASS_VIEW_HC               164
#define IDS_LAYERS                      164
#define IDI_OUTPUT_WND                  165
#define IDS_TYPE                        165
#define IDI_OUTPUT_WND_HC               166
#define IDS_BLEND_MODE                  166
#define IDI_PROPERTIES_WND              167
#define IDS_PROJECTION                  167
#define IDI_PROPERTIES_WND_HC           168
#define IDS_UVMAP                       168
#define IDR_EXPLORER                    169
#define IDS_OPACITY                     169
#define IDB_EXPLORER_24                 170
#define IDS_INVERT                      170
#define IDR_SORT                        171
#define IDS_WIDTH_TILE                  171
#define IDB_SORT_24                     172
#define IDS_HEIGHT_TILE                 172
#define IDR_POPUP_SORT                  173
#define IDS_PIXEL_BLENDING              173
#define IDR_POPUP_EXPLORER              174
#define IDS_IMAGE                       174
#define IDB_FILE_VIEW                   175
#define IDS_BLURRING                    175
#define IDB_FILE_VIEW_24                176
#define IDS_SEAM_ANGLE                  176
#define IDB_CLASS_VIEW                  177
#define IDS_OPTION                      177
#define IDB_CLASS_VIEW_24               178
#define IDS_GAMMA                       178
#define IDR_MENU_IMAGES                 179
#define IDS_SATURATION                  179
#define IDB_MENU_IMAGES_24              180
#define IDS_HUE                         180
#define ID_TOOLS_MACRO                  181
#define IDS_CONTRAST                    181
#define IDR_OUTPUT_POPUP                182
#define IDS_BRIGHTNESS                  182
#define IDR_PROPERTIES                  183
#define IDS_IMAGE_TYPE                  183
#define IDB_PROPERTIES_HC               184
#define IDS_FACE_CULLING                184
#define ID_PROPERTYGRIDPANEWND          185
#define IDS_RENDERER                    186
#define IDR_PDTESTTYPE                  187
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_GLVIEWTYPE                  310
#define ID_VIEW_LIGHTSWND               311
#define IDS_TRUE                        312
#define IDS_FALSE                       313
#define IDB_LIGHTSTOOLBAR_HC            313
#define IDR_FSHADER_TYPE                314
#define IDB_BITMAP1                     315
#define IDB_ADJUSTBTN                   315
#define IDR_POPUP_SURFACE               320
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_VIEW_                        32771
#define ID_VIEW_GL                      32772
#define ID_VIEW_GL32773                 32773
#define ID_BTNADDLIGHT                  32774
#define ID_BUILD_BUILD                  32775
#define ID_BUILD_                       32776
#define ID_BUILD_BUILDPROGRAM           32777
#define ID_BUILD_32778                  32778
#define ID_BUILD_COMPILE                32779
#define ID_SURFACE_OVERRIDEPROGRAM      32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
